# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        "cid": "{428e8fc8-feb7-4fdb-8998-61cde20a7b0b}",
        "contract_ids": ["@mozilla.org/network/protocol/about;1?what=konafox"],
        "esModule": "resource:///modules/AboutKonaFox.sys.mjs",
        "constructor": "AboutKonaFox",
    },
]
